### ISSUE TITLE
Sort by created_at instead of published_at?

### ISSUE THREAD

**Issue by ZakKemble** [tooomm/github-release-stats#43]
The GitHub release pages seems to order by `created_at` date instead of `published_at`. I noticed this when looking at https://tooomm.github.io/github-release-stats/?username=ZakKemble&repository=AVRDUDESS which shows some older releases at the top (I recently uploaded the older stuff just for completeness), unlike [HERE](https://github.com/ZakKemble/AVRDUDESS/releases) were they are correctly shown at the end.

**Comment by tooomm** [comment]
Yes, the page orders by published_at. 
Before, the page did not sort at all and was dependent on the order the API provided, which turned out to not always be reliable back then.
The idea behind this change was to ensure to display the correct and relevant dates/data of a release and ensure a consistent ordering.
You definitely ran into an edge case with creating releases in retrospective that way. :)

If sorting would care for created_at, the [timestamp of the targeted commit of the release tag is used](https://docs.github.com/en/rest/reference/releases#get-the-latest-release), which does not necessarily match the publish date of a release itself and can lead to confusion. Honestly, the last/target commit date will very often mismatch the release date and can vary a lot if e.g. testing is involved.
I'm not even sure if it always used to be like that as I recall issues with pre-releases and their sorting. Maybe draft creation was handled different before.

For reference, here is the data which the API call of your repo returns:
https://api.github.com/repos/ZakKemble/AVRDUDESS/releases


Maybe it's better to sort by created_at, but still display the published_at info of the release, similar to how GitHub does it.
Thanks for opening the issue and raising attention @ZakKemble 👍

**Comment by tooomm** [comment]
I added the changes
